"""add_channel_to_notification_log

Revision ID: 91b03d81c8df
Revises: a1f4cc830d21
Create Date: 2026-04-21 03:21:47.609527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '91b03d81c8df'
down_revision: Union[str, Sequence[str], None] = 'a1f4cc830d21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_logs', sa.Column('channel', sa.String(length=20), nullable=False))
    op.alter_column('tasks', 'scope',
               existing_type=postgresql.ENUM('DAILY', 'WEEKLY', 'MONTHLY', name='task_scope'),
               type_=sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', name='task_scope', native_enum=False),
               existing_nullable=False)
    op.alter_column('tasks', 'priority',
               existing_type=postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', name='task_priority'),
               type_=sa.Enum('LOW', 'MEDIUM', 'HIGH', name='task_priority', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'priority',
               existing_type=sa.Enum('LOW', 'MEDIUM', 'HIGH', name='task_priority', native_enum=False),
               type_=postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', name='task_priority'),
               existing_nullable=False)
    op.alter_column('tasks', 'scope',
               existing_type=sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', name='task_scope', native_enum=False),
               type_=postgresql.ENUM('DAILY', 'WEEKLY', 'MONTHLY', name='task_scope'),
               existing_nullable=False)
    op.drop_column('notification_logs', 'channel')
    # ### end Alembic commands ###
