"""Add last_spawned_at to tasks

Revision ID: 9bc887899219
Revises: a41a5f64d6f6
Create Date: 2026-04-27 02:46:31.169180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bc887899219'
down_revision: Union[str, Sequence[str], None] = 'a41a5f64d6f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('last_spawned_at', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'last_spawned_at')
    # ### end Alembic commands ###
