"""Add recurring task support

Revision ID: a41a5f64d6f6
Revises: 5ead36ba3403
Create Date: 2026-04-27 02:26:28.000610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a41a5f64d6f6'
down_revision: Union[str, Sequence[str], None] = '5ead36ba3403'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('is_recurring', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('tasks', sa.Column('parent_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'tasks', ['parent_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'parent_id')
    op.drop_column('tasks', 'is_recurring')
    # ### end Alembic commands ###
