"""Add is_priority to knowledge_items

Revision ID: a66bc8c79bc2
Revises: 9bc887899219
Create Date: 2026-04-27 02:53:11.047156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a66bc8c79bc2'
down_revision: Union[str, Sequence[str], None] = '9bc887899219'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_items', sa.Column('is_priority', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_items', 'is_priority')
    # ### end Alembic commands ###
